### ISSUE TITLE
نحوه استفاده 

### ISSUE THREAD

**Issue by omidjoon** [mojtaba-khallash/JHazm#4]
با عرض سلام 
ممنون از زحمتی ک کشیدید من میخواستم از این پروژه استفاده کنم اما طریقه استفاده اش یخورده گنگ شده کجا میتونم ی سمپل بهتر گیربیارم ؟

**Comment by mojtaba-khallash** [comment]
سلام
نحوه استفاده در قسمت
[test](https://github.com/mojtaba-khallash/JHazm/tree/master/JHazm/src/test/java/jhazm/test)
قرار دارد
