### ISSUE TITLE
کپی رایت

### ISSUE THREAD

**Issue by omidjoon** [mojtaba-khallash/JHazm#5]
با عرض سلام استفاده از کتابخانه های این پروژه برای مصارف تجاری آزاد است یا خیر؟

**Comment by mojtaba-khallash** [comment]
سلام
بله آزاده
مجوز اين پروژه
[MIT](https://badges.mit-license.org/)
هست

اگر آشنايي با مجوزها نداريد به [اينجا](http://www.dotnettips.info/post/94/%d9%85%d9%82%d8%a7%db%8c%d8%b3%d9%87-%d9%85%d8%ac%d9%88%d8%b2%d9%87%d8%a7%db%8c-%d8%b3%d9%88%d8%b1%d8%b3-%d8%a8%d8%a7%d8%b2) مرجعه نماييد
