### ISSUE TITLE
ساخت jar

### ISSUE THREAD

**Issue by ferish12** [mojtaba-khallash/JHazm#7]
بسازمjarسلام میخوام فایل
میدهMojoFailureExceptionخطای

**Comment by mojtaba-khallash** [comment]
سلام
وقتی از محیط
IDE
استفاده کنید خودش منابع رو به محل درست کپی می کند
ولی وقتی بخواهید با
maven
کار کنید باید دستی منابع رو کپی کنید تا تست ها پاس شود
برای این منظور باید فولدر
resources
در مسیر
```JHazm\src\test\resources\```
کپی شود

دقت کنید مسیر نهایی بصورت زیر باشد
```JHazm\src\test\resources\resources\...```

**Comment by ferish12** [comment]
از راهنمایی ممنون وسپاسگزارم
